/**
 * The admin design system (P0) — the design's own components, ported from
 * designs/_unpacked/P13.template.html with line-number citations at each one.
 *
 * Everything the admin panel draws comes from here. In particular:
 *   · icons are the DESIGN's 57 icons, generated by scripts/gen-admin-icons.mjs
 *   · the user-side `components/ui/*` and `components/ui/Icon` are NOT used in
 *     admin — mixing the two is what made the first attempt's sizing drift
 */

export * from "./icons";
export * from "./admin-context";
export * from "./primitives";
export * from "./tables";
export * from "./overlays";
export * from "./panel-stack";
export * from "./nav";
export * from "./screens";
export * from "./shell";
export * from "./toast";
